### ISSUE TITLE
.flake8 config file not used

### ISSUE THREAD

**Issue by JeromeCorre** [mattijn/pycodestyle_magic#16]
Hi mattijn

Using your magic flake8 within jupyterlab works well for me, except that it does not seem to take into account my local .flake8 config file (to set longer line length)

the .flake8  file is in the same directory as ma .ipynb
am I missing something obvious?

Jerome

**Comment by mattijn** [comment]
Thanks for raising the issue!

I tried before as well to use the `.flake8` config file, but also had some issues and not sure what goes wrong.

But in https://github.com/mattijn/pycodestyle_magic/pull/17 I've added the `--max_line_length` option (and `--ignore`)

So now one can do:
```
%flake8_on --max_line_length 119
```
To set the line length to `119` characters instead of the default `79`.

(available in version >= `0.5`)

**Comment by JeromeCorre** [comment]
Thanks mattijn, that's great
